name: Deploy Azure Web App
on:
  push:
    paths:
      - 'app/**'
  workflow_dispatch:

env:
  REGISTRY_LOGIN_SERVER: 'asaurasacr.azurecr.io'
  IMAGE_BASE_NAME: 'asauras-ex3'
  AZURE_WEBAPP_NAME: 'asauras-ex3'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Login to Docker'
      uses: azure/docker-login@v1
      with:
        login-server: ${{env.REGISTRY_LOGIN_SERVER}}
        username: ${{ env.REGISTRY_USERNAME }}
        password: ${{ env.REGISTRY_PASSWORD }}

    - name: Set image version
      id: image-version
      run: echo "::set-output name=version::$(echo ${GITHUB_REF#refs/heads/})-$(date +'%Y.%m.%d.%H.%M')"

    - name: 'Build and push image'
      working-directory: ./app
      run: |
        docker build . -t ${{ env.REGISTRY_LOGIN_SERVER}}/${{ env.IMAGE_BASE_NAME }}:${{ steps.image-version.outputs.version }}
        docker build . -t ${{ env.REGISTRY_LOGIN_SERVER}}/${{ env.IMAGE_BASE_NAME }}:${{ github.ref_name }}-latest
        docker push ${{ env.REGISTRY_LOGIN_SERVER}}/${{ env.IMAGE_BASE_NAME }}:${{ steps.image-version.outputs.version }}
        docker push ${{ env.REGISTRY_LOGIN_SERVER}}/${{ env.IMAGE_BASE_NAME }}:${{ github.ref_name }}-latest

    - name: Deploy Azure Web App
      id: deploy-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        images: ${{ env.REGISTRY_LOGIN_SERVER}}/${{ env.IMAGE_BASE_NAME }}:${{ needs.build.outputs.image-version }}